version: 2

builds:
  -
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64

kos:
  - repositories: [ghcr.io/sunet/sunet-cdn-manager]
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: none
