package cdntypes

import (
	"net/netip"
	"slices"
	"time"

	"github.com/danielgtaylor/huma/v2"
	"github.com/jackc/pgx/v5/pgtype"
)

const (
	// AuthLoginPath is the HTTP path for the login endpoint.
	AuthLoginPath = "/auth/login"
	// AuthLogoutPath is the HTTP path for the logout endpoint.
	AuthLogoutPath = "/auth/logout"

	DefaultOriginGroupName = "default"
)

// AuthData represents authentication data for a given user or org client credential.
// The Username and UserID fields are only set for users, not org client
// credentials and OrgID/OrgName may be unset for users not currently members
// of an organization.
type AuthData struct {
	Username           *string
	UserID             *pgtype.UUID
	OrgID              *pgtype.UUID
	OrgName            *string
	Superuser          bool
	RoleID             pgtype.UUID
	RoleName           string
	ClientCredName     *string
	ClientCredID       *pgtype.UUID
	ClientCredClientID *string
}

// Types that can be shared across the other packages
type Org struct {
	ID               pgtype.UUID `json:"id" doc:"ID of organization, UUIDv4"`
	Name             string      `json:"name" example:"my-org" doc:"name of organization"`
	ServiceQuota     int64       `json:"service_quota" example:"1" doc:"maximum number of services allowed"`
	DomainQuota      int64       `json:"domain_quota" example:"5" doc:"maximum number of domains allowed"`
	ClientTokenQuota int64       `json:"client_token_quota" example:"10" doc:"maximum number of client tokens allowed"`
}

type OrgListItem struct {
	Org
	ServiceCount     int64 `json:"service_count"`
	DomainCount      int64 `json:"domain_count"`
	ClientTokenCount int64 `json:"client_token_count"`
}

// OrgClientCredentialSafe contains the fields we can share with users via e.g. the API
type OrgClientCredentialSafe struct {
	ID          pgtype.UUID `json:"id" doc:"ID of organization client token, UUIDv4"`
	Name        string      `json:"name" example:"credential-1" doc:"name of client credential"`
	OrgID       pgtype.UUID `json:"org_id" doc:"ID of related organization"`
	ClientID    string      `json:"client_id" doc:"client_id of client credential"`
	Description string      `json:"description" doc:"Description for client token"`
}

// OrgClientCredential maps directly to the fields in the database and contains
// fields that can not be shared directly with users.
type OrgClientCredential struct {
	OrgClientCredentialSafe
	CryptRegistrationAccessToken []byte `json:"crypt_registration_access_token"`
}

// NewOrgClientCredential is returned when creating new client creds and this
// is because the client secret is not stored in the database (only in
// keycloak), so it is only available at creation time for displaying once to
// the requesting client. The data we have in the database lives in
// OrgClientCredential instead.
type NewOrgClientCredential struct {
	OrgClientCredentialSafe
	ClientSecret string `json:"client_secret" doc:"client secret generated by Keycloak, only displayed once at creation time"` // #nosec G117 -- Is expected to be returned to client
}

// OrgClientRegistrationTokenReEncryptResult is returned when requesting re-encryption of all org client registration tokens
type OrgClientRegistrationTokenReEncryptResult struct {
	TotalTokens   int64         `json:"total_tokens" doc:"total number of org client registration tokens that was inspected"`
	UpdatedTokens int64         `json:"updated_tokens" doc:"number of org client registration tokens that was re-encrypted"`
	SkippedTokens int64         `json:"skipped_tokens" doc:"number of org client registration tokens that was already up to date"`
	FailedTokens  int64         `json:"failed_tokens" doc:"number of org client registration tokens that failed to be re-encrypted"`
	Duration      time.Duration `json:"duration" doc:"the amount of time it took to perform the operation"`
}

type Service struct {
	ID            pgtype.UUID `json:"id" doc:"ID of service"`
	Name          string      `json:"name" example:"my-service" doc:"name of service"`
	OrgID         pgtype.UUID `json:"org_id" doc:"ID of related organization"`
	OrgName       string      `json:"org_name" doc:"Name of related organization"`
	UIDRangeFirst int64       `json:"uid_range_first" doc:"First process UID allocated to this service" db:"uid_range_first"`
	UIDRangeEnd   int64       `json:"uid_range_last" doc:"Last UID allocated to this service" db:"uid_range_last"`
	DisabledAt    *time.Time  `json:"disabled_at" db:"disabled_at" doc:"When the service was disabled, null if the service is enabled"`
}

type ServiceVersion struct {
	ID          pgtype.UUID `json:"id" doc:"ID of the service version"`
	ServiceID   pgtype.UUID `json:"service_id" doc:"ID of related service"`
	ServiceName string      `json:"service_name" doc:"Name of related service"`
	OrgID       pgtype.UUID `json:"org_id" doc:"ID of related organization"`
	OrgName     string      `json:"org_name" doc:"Name of related organization"`
	Version     int64       `json:"version" example:"1" doc:"Version of the service"`
	Active      bool        `json:"active" example:"true" doc:"If the version is active"`
	Description string      `json:"description" doc:"Description of the service version" maxLength:"512"`
}

type ServiceVersionVCL struct {
	ServiceVersion
	VCL string `json:"vcl" example:"varnish vcl" doc:"VCL content"`
}

// A combined type of all related data for a service version
type ServiceVersionConfig struct {
	ServiceVersion
	VCLTemplate        string         `json:"vcl_template" doc:"The VCL template content"`
	ServiceIPAddresses []netip.Addr   `json:"service_ip_addresses" doc:"The IP (v4 and v6) addresses allocated to the service" validate:"min=2"`
	Domains            []DomainString `json:"domains" doc:"The domains used by the VCL" validate:"min=1"`
	OriginGroups       []OriginGroup  `json:"origin_groups" doc:"The available origin groups" validate:"min=1"`
	Origins            []Origin       `json:"origins" doc:"The origins used by the VCL" validate:"min=1"`
}

type ServiceVersionCloneData struct {
	VCLTemplate  string         `json:"vcl_template" doc:"The VCL template content"`
	Description  string         `json:"description" doc:"The description of the cloned service version"`
	Domains      []DomainString `json:"domains" doc:"The domains used by the VCL" validate:"min=1"`
	OriginGroups []OriginGroup  `json:"origin_groups" doc:"The origin groups of the cloned version"`
	Origins      []Origin       `json:"origins" doc:"The origins used by the VCL" validate:"min=1"`
}

// What data is expected when handling a request to add a service version
type InputServiceVersion struct {
	ServiceVersion
	VCLTemplate             string                        `json:"vcl_template" doc:"The VCL template content" validate:"min=1,max=1048576"`
	Domains                 []DomainString                `json:"domains" doc:"The domains used by the VCL" validate:"min=1"`
	ConditionalOriginGroups []InputConditionalOriginGroup `json:"conditional_origin_groups" doc:"Ordered conditional origin groups; list order is selection priority" validate:"dive"`
	DefaultOriginGroup      InputDefaultOriginGroup       `json:"default_origin_group" doc:"Fallback origin group used when no condition matches"`
}

type CreateServiceVersionOrigin struct {
	OriginHost      string `schema:"host" validate:"min=1,max=253"`
	OriginPort      int    `schema:"port" validate:"gte=1,lte=65535"`
	OriginTLS       bool   `schema:"tls"`
	OriginVerifyTLS bool   `schema:"verify-tls"`
}

type CreateServiceVersionConditionalGroup struct {
	Name      string                       `schema:"name" validate:"min=1,max=63"`
	Condition string                       `schema:"condition" validate:"min=1"`
	Origins   []CreateServiceVersionOrigin `schema:"origins" validate:"min=1,max=10,dive"`
}

type CreateServiceVersionDefaultGroup struct {
	Origins []CreateServiceVersionOrigin `schema:"origins" validate:"min=1,max=10,dive"`
}

type CreateServiceVersionForm struct {
	VCLTemplate       string                                 `schema:"vcl_template" validate:"min=1,max=1048576"`
	Description       string                                 `schema:"description" validate:"max=512"`
	Domains           []DomainString                         `schema:"domains" validate:"dive,min=1,max=253"`
	ConditionalGroups []CreateServiceVersionConditionalGroup `schema:"conditional-origin-groups" validate:"max=10,dive"`
	DefaultGroup      CreateServiceVersionDefaultGroup       `schema:"default-origin-group"`
}

// Field order matters: queries aggregating origin groups build
// (id, default_group, name, condition, position) records that pgx
// decodes into this struct positionally, so the fields must stay in
// that order and new fields must be added to those records as well.
type OriginGroup struct {
	ID           pgtype.UUID `json:"id" doc:"ID of origin group"`
	DefaultGroup bool        `json:"defaut_group" example:"true" doc:"If the group is the default"`
	Name         string      `json:"name"`
	Condition    *string     `json:"condition,omitempty" doc:"VCL condition selecting this group; nil for the default group"`
	Position     int64       `json:"position" doc:"Selection chain position within the service version"`
}

type NodeGroup struct {
	ID          pgtype.UUID `json:"id" doc:"ID of node group"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

type InputOrigin struct {
	Host      string `json:"host" minLength:"1" maxLength:"253"`
	Port      int    `json:"port" minimum:"1" maximum:"65535"`
	TLS       bool   `json:"tls"`
	VerifyTLS bool   `json:"verify_tls"`
}

type InputConditionalOriginGroup struct {
	Name      string        `json:"name" doc:"Name of origin group" minLength:"1" maxLength:"63" pattern:"^[a-z]([-a-z0-9]*[a-z0-9])?$" patternDescription:"valid DNS label" validate:"min=1,max=63"`
	Condition string        `json:"condition" doc:"VCL boolean expression selecting this group" minLength:"1" validate:"min=1"`
	Origins   []InputOrigin `json:"origins" doc:"Origins belonging to this group" minItems:"1" maxItems:"10" validate:"min=1,dive"`
}

type InputDefaultOriginGroup struct {
	Origins []InputOrigin `json:"origins" doc:"Origins belonging to the default group" minItems:"1" maxItems:"10" validate:"min=1,dive"`
}

type Origin struct {
	OriginGroupID pgtype.UUID `json:"origin_group_id" doc:"ID of origin group"`
	Host          string      `json:"host" minLength:"1" maxLength:"253"`
	Port          int         `json:"port" minimum:"1" maximum:"65535"`
	TLS           bool        `json:"tls"`
	VerifyTLS     bool        `json:"verify_tls"`
}

const (
	// VCLMacroPrefix is the prefix used for VCL macro comments that mark
	// system-generated content injection points.
	VCLMacroPrefix = "#SUNET-CDN-MANAGER "

	// VCLTemplateMaxSize is the maximum size of a VCL template in bytes (1MB).
	VCLTemplateMaxSize = 1048576
)

// VCL macro name constants.
const (
	VCLMacroPreamble        = "preamble"
	VCLMacroRecv            = "vcl_recv"
	VCLMacroPipe            = "vcl_pipe"
	VCLMacroPass            = "vcl_pass"
	VCLMacroHash            = "vcl_hash"
	VCLMacroPurge           = "vcl_purge"
	VCLMacroMiss            = "vcl_miss"
	VCLMacroHit             = "vcl_hit"
	VCLMacroDeliver         = "vcl_deliver"
	VCLMacroSynth           = "vcl_synth"
	VCLMacroBackendFetch    = "vcl_backend_fetch"
	VCLMacroBackendResponse = "vcl_backend_response"
	VCLMacroBackendError    = "vcl_backend_error"
)

// vclRequiredMacros lists all macro names that must appear exactly once in a
// VCL template. The "preamble" macro marks where the system-generated VCL
// version, imports, and backend definitions are injected. The remaining
// macros each correspond to a Varnish subroutine.
var vclRequiredMacros = []string{
	VCLMacroPreamble,
	VCLMacroRecv,
	VCLMacroPipe,
	VCLMacroPass,
	VCLMacroHash,
	VCLMacroPurge,
	VCLMacroMiss,
	VCLMacroHit,
	VCLMacroDeliver,
	VCLMacroSynth,
	VCLMacroBackendFetch,
	VCLMacroBackendResponse,
	VCLMacroBackendError,
}

// VCLRequiredMacros returns a copy of the required macro names list.
func VCLRequiredMacros() []string {
	return slices.Clone(vclRequiredMacros)
}

// DefaultVCLTemplate is the minimal valid VCL template containing all required
// macros. It is used as the starting point for new service versions.
const DefaultVCLTemplate = `#SUNET-CDN-MANAGER preamble

sub vcl_recv {
#SUNET-CDN-MANAGER vcl_recv
}

sub vcl_pipe {
#SUNET-CDN-MANAGER vcl_pipe
}

sub vcl_pass {
#SUNET-CDN-MANAGER vcl_pass
}

sub vcl_hash {
#SUNET-CDN-MANAGER vcl_hash
}

sub vcl_purge {
#SUNET-CDN-MANAGER vcl_purge
}

sub vcl_miss {
#SUNET-CDN-MANAGER vcl_miss
}

sub vcl_hit {
#SUNET-CDN-MANAGER vcl_hit
}

sub vcl_deliver {
#SUNET-CDN-MANAGER vcl_deliver
}

sub vcl_synth {
#SUNET-CDN-MANAGER vcl_synth
}

sub vcl_backend_fetch {
#SUNET-CDN-MANAGER vcl_backend_fetch
}

sub vcl_backend_response {
#SUNET-CDN-MANAGER vcl_backend_response
}

sub vcl_backend_error {
#SUNET-CDN-MANAGER vcl_backend_error
}`

type Domain struct {
	ID                pgtype.UUID `json:"id"`
	FQDN              string      `json:"fqdn"`
	Verified          bool        `json:"verified"`
	VerificationToken string      `json:"verification_token"`
}

type Node struct {
	ID          pgtype.UUID  `json:"id" doc:"ID of the node"`
	Name        string       `json:"name" doc:"Name of the node"`
	Description string       `json:"description" doc:"some identifying info for the node" minLength:"1" maxLength:"100" `
	Addresses   []netip.Addr `json:"addresses,omitempty" doc:"The IPv4 and IPv6 addresses of the node"`
	Maintenance bool         `json:"maintenance" doc:"If the node is currently in maintenance mode"`
}

type CacheNode struct {
	Node
}

type L4LBNode struct {
	Node
}

type CacheNodeListItem struct {
	CacheNode
	NodeGroupID   *pgtype.UUID `json:"node_group_id"`
	NodeGroupName *string      `json:"node_group_name"`
}

type L4LBNodeListItem struct {
	L4LBNode
	NodeGroupID   *pgtype.UUID `json:"node_group_id"`
	NodeGroupName *string      `json:"node_group_name"`
}

type IPNetworkListItem struct {
	ID        pgtype.UUID  `json:"id"`
	Network   netip.Prefix `json:"network"`
	Allocated int64        `json:"allocated"`
}

type L4LBNodeConfig struct {
	L4LBNode   L4LBNode              `json:"l4lb_node"`
	IPNetworks []netip.Prefix        `json:"ip_networks"`
	Services   []ServiceConnectivity `json:"service_ip_info"`
	CacheNodes []CacheNode           `json:"cache_nodes"`
}

type ServiceConnectivity struct {
	ServiceID          pgtype.UUID  `json:"service_id"`
	ServiceIPAddresses []netip.Addr `json:"service_ip_addresses"`
	HTTPS              bool         `json:"https"`
	HTTP               bool         `json:"http"`
}

// CacheNodeConfig is a nested struct containing complete config for a cache
// node optimized for easy iteration over the contents and minimal duplication
// of fields.
//
// Map key is string rather than pgtype.UUID to support JSON marshalling.
// Trying to use pgtype.UUID directly as a map key leads to
// "json: unsupported type: map[pgtype.UUID]string"
// because pgtype.UUID does not implement encoding.TextMarshaler as expected by
// encoding/json.
type CacheNodeConfig struct {
	CacheNode  CacheNode                  `json:"cache_node"`
	IPNetworks []netip.Prefix             `json:"ip_networks"`
	L4LBNodes  []L4LBNode                 `json:"l4lb_nodes"`
	Orgs       map[string]OrgWithServices `json:"orgs"`
}

type OrgWithServices struct {
	ID       pgtype.UUID                    `json:"id"`
	Services map[string]ServiceWithVersions `json:"services"`
}

type ServiceWithVersions struct {
	ID              pgtype.UUID                        `json:"id"`
	IPAddresses     []netip.Addr                       `json:"ip_addresses"`
	UIDRangeFirst   int64                              `json:"uid_range_first"`
	UIDRangeLast    int64                              `json:"uid_range_last"`
	ServiceVersions map[int64]ServiceVersionWithConfig `json:"service_versions"`
}

type ServiceVersionWithConfig struct {
	ID            pgtype.UUID    `json:"id"`
	Version       int64          `json:"version" example:"1" doc:"Version of the service"`
	Active        bool           `json:"active" example:"true" doc:"If the version is active"`
	VCL           string         `json:"vcl"`
	TLS           bool           `json:"tls" example:"true" doc:"If at least one origin has TLS enabled which means we require certificates"`
	Domains       []DomainString `json:"domains" doc:"FQDNs that the service is listening on"`
	HAProxyConfig string         `json:"haproxy_config"`
}

type DomainString string

func (ds DomainString) Schema(_ huma.Registry) *huma.Schema {
	return &huma.Schema{
		Type:      "string",
		MinLength: new(1),
		MaxLength: new(253),
	}
}

func (ds DomainString) String() string {
	return string(ds)
}

// Organization names must be a valid DNS label so this is can not collide
// with a real name.
const OrgNotSelected = "-- not selected --"

// LocalAuthProvider is the auth provider name for users with local
// (password-based) authentication, as opposed to external providers like
// Keycloak/OIDC.
const LocalAuthProvider = "local"

// KeycloakAuthProvider is the auth provider name for users authenticated
// via Keycloak/OIDC.
const KeycloakAuthProvider = "keycloak"

type Role struct {
	ID        pgtype.UUID `json:"id" doc:"ID of role"`
	Name      string      `json:"name" example:"user" doc:"name of role"`
	Superuser bool        `json:"superuser" doc:"whether this role grants superuser access"`
}

type UserListItem struct {
	ID           pgtype.UUID `json:"id"`
	DisplayName  string      `json:"display_name"`
	RoleName     string      `json:"role_name"`
	OrgName      *string     `json:"org_name"`
	AuthProvider string      `json:"auth_provider"`
}

// UserEditData is a composite type for the console edit form, enriching the
// base user fields with resolved names and auth provider info.
type UserEditData struct {
	ID           pgtype.UUID
	DisplayName  string
	RoleName     string
	OrgName      *string
	AuthProvider string // "local" or "keycloak"
}

type DashboardData struct {
	ResourceAccess   bool
	OrgDashboard     bool
	ServiceQuota     int64
	ServiceUsed      int64
	DomainQuota      int64
	DomainUsed       int64
	ClientCredsQuota int64
	ClientCredsUsed  int64
}
